//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by graphstudio.rc
//
#define IDD_ABOUTBOX                    100
#define IDP_OLE_INIT_FAILED             100
#define IDD_DIALOGBAR                   103
#define IDD_BAR_SEEKING                 103
#define IDD_DIALOG_FILTERDETAILS        105
#define IDR_MAINFRAME                   128
#define IDR_graphstudioTYPE             129
#define IDB_BITMAP_LOGO                 130
#define IDR_TOOLBAR1                    131
#define IDD_DIALOG_FILTERS              134
#define IDD_DIALOG_EVENTS               135
#define IDD_DIALOG_TEXTVIEW             136
#define IDD_DIALOG_ASYNCOPEN            137
#define IDD_DIALOG_PROPERTYPAGE         138
#define IDD_DIALOG_ROT                  141
#define IDD_DIALOG_ASYNCOPEN1           142
#define IDD_DIALOG_FILESINK             142
#define IDD_DIALOG_FAVORITES            143
#define IDB_BITMAP_TREE                 144
#define IDR_MENU_FAVORITES              145
#define IDD_DIALOG_NEWGROUP             146
#define IDD_DIALOG_RENDERURL            147
#define IDC_COMBO_CATEGORIES            1001
#define IDC_LIST_FILTERS                1002
#define IDC_COMBO_MERIT                 1003
#define IDC_BUTTON_REGISTRY             1004
#define IDC_LIST_DETAILS                1005
#define IDC_CHECK_FAVORITE              1006
#define IDC_BUTTON_PROPERTYPAGE         1007
#define IDC_BUTTON3                     1008
#define IDC_BUTTON_UNREGISTER           1008
#define IDC_BUTTON_COPYTEXT             1008
#define IDC_BUTTON_INSERT               1009
#define IDC_BUTTON_MEDIATYPES           1010
#define IDC_STATIC_TITLE                1011
#define IDC_STATIC_SEPARATOR            1012
#define IDC_BUTTON_CLEAR                1013
#define IDC_LIST_EVENTS                 1014
#define IDC_BUTTON2                     1015
#define IDC_BUTTON_COPY                 1015
#define IDC_BUTTON_REFRESH              1015
#define IDC_SLIDER1                     1016
#define IDC_SLIDER_SEEK                 1016
#define IDC_STATIC_TIME                 1017
#define IDC_BUTTON1                     1018
#define IDC_BUTTON_BROWSE               1018
#define IDC_BUTTON_APPLY                1018
#define IDC_EDIT_DETAILS                1019
#define IDC_COMBO_REPORTTYPE            1020
#define IDC_RADIO_FILE                  1021
#define IDC_RADIO_URL                   1022
#define IDC_COMBO_FILE                  1023
#define IDC_COMBO_URL                   1024
#define IDC_TAB1                        1025
#define IDC_TAB_PAGES                   1025
#define IDC_TITLEBAR                    1027
#define IDC_TITLE                       1028
#define IDC_LIST_GRAPHS                 1029
#define IDC_BUTTON_CONNECT              1030
#define IDC_TREE_FAVORITES              1030
#define IDC_EDIT1                       1031
#define IDC_EDIT_NAME                   1031
#define IDC_TREE1                       1033
#define IDC_TREE                        1033
#define ID_LIST_MRU_CLEAR               4999
#define ID_LIST_MRU_FILE0               5000
#define ID_AUDIO_RENDERER0              6000
#define ID_VIDEO_RENDERER0              6100
#define ID_FAVORITE_FILTER              6200
#define ID_Menu                         32771
#define ID_FILE_RENDERURL               32772
#define ID_FILE_RENDERDVD               32773
#define ID_FILE_RENDERCAPTURE           32774
#define ID_FILE_CONNECTTOREMOTEGRAPH    32775
#define ID_FILE_DISCONNECTFROMREMOTEGRAPH 32776
#define ID_BUTTON_PLAY                  32777
#define ID_BUTTON_PAUSE                 32778
#define ID_BUTTON_STOP                  32779
#define ID_FILE_RENDERFILE              32780
#define ID_GRAPH_INSERTFILTER           32781
#define ID_VIEW_GRAPHEVENTS             32782
#define ID_VIEW_SEEKINGBAR              32783
#define ID_VIEW_TEXTINFORMATION         32784
#define ID_GRAPH_INSERTFILESOURCE       32785
#define ID_PROPERTYPAGE                 32786
#define ID_PIN_RENDER                   32787
#define ID_GRAPH_MAKEGRAPHSCREENSHOT    32788
#define ID_VIEW_50                      32794
#define ID_VIEW_75                      32795
#define ID_VIEW_100                     32796
#define ID_VIEW_150                     32797
#define ID_VIEW_200                     32798
#define ID_BUTTON_ADD_FILTERS           32799
#define ID_GRAPH_INSERTFILEWRITER       32805
#define ID_GRAPH_INSERTVIDEORENDERER    32806
#define ID_GRAPH_INSERTAUDIORENDERER    32807
#define ID_FILE_ADDMEDIAFILE            32808
#define ID_FILTERS_DOUBLESELECTEDFILTERS 32809
#define ID_VIEW_DECREASEZOOMLEVEL       32812
#define ID_VIEW_INCREASEZOOMLEVEL       32813
#define ID_FILTERS_MANAGEFAVORITES      32818
#define ID_MENU_CREATEGROUP             32819
#define ID_MENU_REMOVEGROUP             32820
#define ID_MENU_REMOVEFILTER            32821
#define ID_OPTIONS_AUTOMATICRESTART     32822
#define ID_AUTOMATICRESTART_DISABLED    32823
#define ID_AUTOMATICRESTART_EVERYHOUR   32824
#define ID_AUTOMATICRESTART_EVERYTWOHOURS 32825
#define ID_AUTOMATICRESTART_EVERY4HOURS 32826
#define ID_AUTOMATICRESTART_AT04        32827
#define ID_AUTORESTART                  32828
#define ID_AUTORESTART_DISABLED         32829
#define ID_FILE_OPENFROMXML             32830
#define ID_FILE_SAVEASXML               32831
#define ID_OPTIONS_DISPLAYFILTERNAME    32832
#define ID_OPTIONS_DISPLAYASFILENAME    32833
#define ID_BUTTON32834                  32834
#define ID_BUTTON_DIRECT                32834
#define ID_OPTIONS_DIRECTCONNECTMODE    32835
#define IDC_OPTIONS_DIRECT              32836
#define ID_OPTIONS_DIRECT               32837
#define ID_BUTTON_STEP                  32838
#define ID_BUTTON_PLAYPAUSE             32841

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        148
#define _APS_NEXT_COMMAND_VALUE         32843
#define _APS_NEXT_CONTROL_VALUE         1034
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
