//-----------------------------------------------------------------------------
//
//	MONOGRAM GraphStudio
//
//	Author : Igor Janos
//
//-----------------------------------------------------------------------------
#include "stdafx.h"

namespace GraphStudio
{

#define	KNOWN(x)			{ x, _T( # x ) }
	struct GuidPair {
		GUID	guid; 
		LPCTSTR	name;
	};

	const GuidPair	KnownGuidList[] = 
	{
		// filters
		KNOWN(CLSID_AsyncReader),
		KNOWN(GUID_NULL),

		// Media Types
		KNOWN(MEDIATYPE_AnalogAudio),
		KNOWN(MEDIATYPE_AnalogVideo),
		KNOWN(MEDIATYPE_Audio),
		KNOWN(MEDIATYPE_AUXLine21Data),
		KNOWN(MEDIATYPE_DTVCCData),
		KNOWN(MEDIATYPE_DVD_ENCRYPTED_PACK),
		KNOWN(MEDIATYPE_DVD_NAVIGATION),
		KNOWN(MEDIATYPE_File),
		KNOWN(MEDIATYPE_Interleaved),
		KNOWN(MEDIATYPE_LMRT),
		KNOWN(MEDIATYPE_Midi),
		KNOWN(MEDIATYPE_MPEG1SystemStream),
		KNOWN(MEDIATYPE_MPEG2_PACK),
		KNOWN(MEDIATYPE_MPEG2_PES),
		KNOWN(MEDIATYPE_MSTVCaption),
		KNOWN(MEDIATYPE_NULL),
		KNOWN(MEDIATYPE_ScriptCommand),
		KNOWN(MEDIATYPE_Stream),
		KNOWN(MEDIATYPE_Text),
		KNOWN(MEDIATYPE_Timecode),
		KNOWN(MEDIATYPE_URL_STREAM),
		KNOWN(MEDIATYPE_VBI),
		KNOWN(MEDIATYPE_Video),

		// SubTypes
		KNOWN(MEDIASUBTYPE_A2B10G10R10),
		KNOWN(MEDIASUBTYPE_A2R10G10B10),
		KNOWN(MEDIASUBTYPE_AI44),
		KNOWN(MEDIASUBTYPE_AIFF),
		KNOWN(MEDIASUBTYPE_AnalogVideo_NTSC_M),
		KNOWN(MEDIASUBTYPE_AnalogVideo_PAL_B),
		KNOWN(MEDIASUBTYPE_AnalogVideo_PAL_D),
		KNOWN(MEDIASUBTYPE_AnalogVideo_PAL_G),
		KNOWN(MEDIASUBTYPE_AnalogVideo_PAL_H),
		KNOWN(MEDIASUBTYPE_AnalogVideo_PAL_I),
		KNOWN(MEDIASUBTYPE_AnalogVideo_PAL_M),
		KNOWN(MEDIASUBTYPE_AnalogVideo_PAL_N),
		KNOWN(MEDIASUBTYPE_AnalogVideo_PAL_N_COMBO),
		KNOWN(MEDIASUBTYPE_AnalogVideo_SECAM_B),
		KNOWN(MEDIASUBTYPE_AnalogVideo_SECAM_D),
		KNOWN(MEDIASUBTYPE_AnalogVideo_SECAM_G),
		KNOWN(MEDIASUBTYPE_AnalogVideo_SECAM_H),
		KNOWN(MEDIASUBTYPE_AnalogVideo_SECAM_K),
		KNOWN(MEDIASUBTYPE_AnalogVideo_SECAM_K1),
		KNOWN(MEDIASUBTYPE_AnalogVideo_SECAM_L),
		KNOWN(MEDIASUBTYPE_ARGB1555),
		KNOWN(MEDIASUBTYPE_ARGB1555_D3D_DX7_RT),
		KNOWN(MEDIASUBTYPE_ARGB1555_D3D_DX9_RT),
		KNOWN(MEDIASUBTYPE_ARGB32),
		KNOWN(MEDIASUBTYPE_ARGB32_D3D_DX7_RT),
		KNOWN(MEDIASUBTYPE_ARGB32_D3D_DX9_RT),
		KNOWN(MEDIASUBTYPE_ARGB4444),
		KNOWN(MEDIASUBTYPE_ARGB4444_D3D_DX7_RT),
		KNOWN(MEDIASUBTYPE_ARGB4444_D3D_DX9_RT),
		KNOWN(MEDIASUBTYPE_Asf),
		KNOWN(MEDIASUBTYPE_AU),
		KNOWN(MEDIASUBTYPE_Avi),
		KNOWN(MEDIASUBTYPE_AYUV),
		KNOWN(MEDIASUBTYPE_CFCC),
		KNOWN(MEDIASUBTYPE_CLJR),
		KNOWN(MEDIASUBTYPE_CLPL),
		KNOWN(MEDIASUBTYPE_CPLA),
		KNOWN(MEDIASUBTYPE_DOLBY_AC3),
		KNOWN(MEDIASUBTYPE_DOLBY_AC3_SPDIF),
		KNOWN(MEDIASUBTYPE_DRM_Audio),
		KNOWN(MEDIASUBTYPE_DssAudio),
		KNOWN(MEDIASUBTYPE_DssVideo),
		KNOWN(MEDIASUBTYPE_DTS),
		KNOWN(MEDIASUBTYPE_DtvCcData),
		KNOWN(MEDIASUBTYPE_dv25),
		KNOWN(MEDIASUBTYPE_dv50),
		KNOWN(MEDIASUBTYPE_DVCS),
		KNOWN(MEDIASUBTYPE_DVD_LPCM_AUDIO),
		KNOWN(MEDIASUBTYPE_DVD_NAVIGATION_DSI),
		KNOWN(MEDIASUBTYPE_DVD_NAVIGATION_PCI),
		KNOWN(MEDIASUBTYPE_DVD_NAVIGATION_PROVIDER),
		KNOWN(MEDIASUBTYPE_DVD_SUBPICTURE),
		KNOWN(MEDIASUBTYPE_dvh1),
		KNOWN(MEDIASUBTYPE_dvhd),
		KNOWN(MEDIASUBTYPE_DVSD),
		KNOWN(MEDIASUBTYPE_dvsd),
		KNOWN(MEDIASUBTYPE_dvsl),
		KNOWN(MEDIASUBTYPE_H264),
		KNOWN(MEDIASUBTYPE_IA44),
		KNOWN(MEDIASUBTYPE_IEEE_FLOAT),
		KNOWN(MEDIASUBTYPE_IF09),
		KNOWN(MEDIASUBTYPE_IJPG),
		KNOWN(MEDIASUBTYPE_IMC1),
		KNOWN(MEDIASUBTYPE_IMC2),
		KNOWN(MEDIASUBTYPE_IMC3),
		KNOWN(MEDIASUBTYPE_IMC4),
		KNOWN(MEDIASUBTYPE_IYUV),
		KNOWN(MEDIASUBTYPE_Line21_BytePair),
		KNOWN(MEDIASUBTYPE_Line21_GOPPacket),
		KNOWN(MEDIASUBTYPE_Line21_VBIRawData),
		KNOWN(MEDIASUBTYPE_MDVF),
		KNOWN(MEDIASUBTYPE_MJPG),
		KNOWN(MEDIASUBTYPE_MPEG1Audio),
		KNOWN(MEDIASUBTYPE_MPEG1AudioPayload),
		KNOWN(MEDIASUBTYPE_MPEG1Packet),
		KNOWN(MEDIASUBTYPE_MPEG1Payload),
		KNOWN(MEDIASUBTYPE_MPEG1System),
		KNOWN(MEDIASUBTYPE_MPEG1Video),
		KNOWN(MEDIASUBTYPE_MPEG1VideoCD),
		KNOWN(MEDIASUBTYPE_MPEG2_AUDIO),
		KNOWN(MEDIASUBTYPE_MPEG2_PROGRAM),
		KNOWN(MEDIASUBTYPE_MPEG2_TRANSPORT),
		KNOWN(MEDIASUBTYPE_MPEG2_TRANSPORT_STRIDE),
		KNOWN(MEDIASUBTYPE_MPEG2_UDCR_TRANSPORT),
		KNOWN(MEDIASUBTYPE_MPEG2_VIDEO),
		KNOWN(MEDIASUBTYPE_MPEG2_WMDRM_TRANSPORT),
		KNOWN(MEDIASUBTYPE_None),
		KNOWN(MEDIASUBTYPE_NULL),
		KNOWN(MEDIASUBTYPE_NV12),
		KNOWN(MEDIASUBTYPE_NV24),
		KNOWN(MEDIASUBTYPE_Overlay),
		KNOWN(MEDIASUBTYPE_PCM),
		KNOWN(MEDIASUBTYPE_Plum),
		KNOWN(MEDIASUBTYPE_QTJpeg),
		KNOWN(MEDIASUBTYPE_QTMovie),
		KNOWN(MEDIASUBTYPE_QTRle),
		KNOWN(MEDIASUBTYPE_QTRpza),
		KNOWN(MEDIASUBTYPE_QTSmc),
		KNOWN(MEDIASUBTYPE_RAW_SPORT),
		KNOWN(MEDIASUBTYPE_RGB1),
		KNOWN(MEDIASUBTYPE_RGB24),
		KNOWN(MEDIASUBTYPE_RGB32),
		KNOWN(MEDIASUBTYPE_RGB4),
		KNOWN(MEDIASUBTYPE_RGB555),
		KNOWN(MEDIASUBTYPE_RGB565),
		KNOWN(MEDIASUBTYPE_RGB8),
		KNOWN(MEDIASUBTYPE_S340),
		KNOWN(MEDIASUBTYPE_S342),
		KNOWN(MEDIASUBTYPE_SDDS),
		KNOWN(MEDIASUBTYPE_SPDIF_TAG_241h),
		KNOWN(MEDIASUBTYPE_TELETEXT),
		KNOWN(MEDIASUBTYPE_TVMJ),
		KNOWN(MEDIASUBTYPE_UYVY),
		KNOWN(MEDIASUBTYPE_VPS),
		KNOWN(MEDIASUBTYPE_VPVBI),
		KNOWN(MEDIASUBTYPE_VPVideo),
		KNOWN(MEDIASUBTYPE_WAKE),
		KNOWN(MEDIASUBTYPE_WAVE),
		KNOWN(MEDIASUBTYPE_WSS),
		KNOWN(MEDIASUBTYPE_Y211),
		KNOWN(MEDIASUBTYPE_Y411),
		KNOWN(MEDIASUBTYPE_Y41P),
		KNOWN(MEDIASUBTYPE_YUY2),
		KNOWN(MEDIASUBTYPE_YUYV),
		KNOWN(MEDIASUBTYPE_YV12),
		KNOWN(MEDIASUBTYPE_YVU9),
		KNOWN(MEDIASUBTYPE_YVYU),
	
		// Formats
		KNOWN(FORMAT_525WSS),
		KNOWN(FORMAT_AnalogVideo),
		KNOWN(FORMAT_DolbyAC3),
		KNOWN(FORMAT_DVD_LPCMAudio),
		KNOWN(FORMAT_DvInfo),
		KNOWN(FORMAT_MPEG2_VIDEO),
		KNOWN(FORMAT_MPEG2Audio),
		KNOWN(FORMAT_MPEG2Video),
		KNOWN(FORMAT_MPEGStreams),
		KNOWN(FORMAT_MPEGVideo),
		KNOWN(FORMAT_None),
		KNOWN(FORMAT_VideoInfo),
		KNOWN(FORMAT_VIDEOINFO2),
		KNOWN(FORMAT_VideoInfo2),
		KNOWN(FORMAT_WaveFormatEx)
	};
	const int KnownGuidCount = sizeof(KnownGuidList) / sizeof(KnownGuidList[0]);


	bool NameGuid(GUID guid, CString &str)
	{
		for (int i=0; i<KnownGuidCount; i++) {
			if (KnownGuidList[i].guid == guid) {
				str = CString(KnownGuidList[i].name);
				return true;
			}
		}

		LPOLESTR	str2;
		StringFromCLSID(guid, &str2);
		str = CString(str2);
		CoTaskMemFree(str2);
		return false;
	}

};


